name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        if: secrets.RUN_WORKFLOW == 'true' # Điều kiện để chạy workflow
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: minhtai03/meowchat:latest

    deploy:
        if: secrets.RUN_WORKFLOW == 'true' # Điều kiện để chạy workflow
        runs-on: ubuntu-latest

        needs: build

        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  script: |
                      sudo docker pull minhtai03/meowchat:latest
                      sudo docker stop meowchat_flask_container || true
                      sudo docker rm meowchat_flask_container || true
                      sudo docker run --env-file .env -d -p 5000:5000 --name meowchat_flask_container --restart unless-stopped minhtai03/meowchat:latest
